#!/usr/bin/env python

import sys
import json
from waterpictrl.waterpictrl import WaterPiCtrl 


def main(argv):
    if not argv or len(argv) != 1:
        print('rpi-switch-mqtt <config file>')
    else:
        with open(argv[0]) as data_file:
            config = json.load(data_file)
            server = WaterPiCtrl(config)
            server.start()

if __name__ == "__main__":
    main(sys.argv[1:])